version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map port 5000 on host to 5000 in the container
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3002:3000" # Map port 3002 on host to 3000 in the container
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend